version = 0.1
[staging]
[staging.global.parameters]
region = "us-east-1"
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"
resolve_s3 = true
s3_prefix = "todo-list-aws"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
disable_rollback = true
confirm_changeset = false
fail_on_empty_changeset = false

[production]
[production.global.parameters]
region = "us-east-1"
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
resolve_s3 = true
s3_prefix = "todo-list-aws"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
disable_rollback = true
confirm_changeset = false
fail_on_empty_changeset = false
